//! The one concept this crate is built around: the choice slot — its unlock
//! condition, option source, validators, and effects, all supplied by a
//! ruleset as behavior over its own state type `S`.

use types::{
    ChecklistEntry, Decision, MeterView, OptionView, Selection, SlotId, SlotViewKind, StepId,
};

/// Whether a slot currently takes part in the wizard.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Availability {
    /// Selectable now.
    Open,
    /// Visible but not yet selectable; the reason is shown to the player.
    Locked { reason: String },
    /// Not part of the wizard under the current state (e.g. a replacement
    /// slot that only exists once a collision does). Hidden slots are not
    /// rendered and not validated.
    Hidden,
}

/// A structural rejection from a slot's `apply`: the selection cannot enter
/// the log at all (unknown option, failed prerequisite, wrong shape). This
/// is distinct from checklist `Illegal` entries, which are confirmed states
/// that a validator flags for fixing.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct ApplyError {
    pub message: String,
}

impl ApplyError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// The option catalog under the current state.
pub type OptionsFn<S> = Box<dyn Fn(&S) -> Vec<OptionView> + Send + Sync>;
/// Fold one decision into the state, or reject it structurally.
pub type ApplyFn<S> = Box<dyn Fn(&mut S, &Decision) -> Result<(), ApplyError> + Send + Sync>;
/// Validate the slot against the fully folded state.
pub type ValidateFn<S> = Box<dyn Fn(&S, Option<&Decision>) -> Vec<ChecklistEntry> + Send + Sync>;
/// Always-on gauges for the slot (budgets and the like). Count meters for
/// Multi slots are generated by the engine automatically; register only
/// what the engine cannot know.
pub type MetersFn<S> = Box<dyn Fn(&S, Option<&Decision>) -> Vec<MeterView> + Send + Sync>;

/// Everything a ruleset says about one slot. `S` is the ruleset's folded
/// character state; the engine never looks inside it.
pub struct SlotRegistration<S> {
    pub id: SlotId,
    /// The wizard step this slot renders under.
    pub step: StepId,
    pub label: String,
    /// Whether resolving the slot is required to finalize; optional slots
    /// (flavor text fields) never produce Incomplete entries.
    pub required: bool,
    /// Free-form hint for nicer client widgets; never semantics.
    pub presentation_hint: Option<String>,
    /// How the slot collects a selection, given the current state (counts
    /// may depend on earlier choices).
    pub kind: Box<dyn Fn(&S) -> SlotViewKind + Send + Sync>,
    /// Unlock condition against the current state.
    pub unlock: Box<dyn Fn(&S) -> Availability + Send + Sync>,
    /// Slots whose confirmed decisions become meaningless when this slot's
    /// decision changes (their catalogs derive from it). Clearing this slot
    /// clears them, transitively.
    pub dependents: Vec<SlotId>,
    /// The option catalog under the current state (empty for text slots).
    pub options: OptionsFn<S>,
    /// Fold this slot's decision into the state. Structural errors reject
    /// the decision outright; a tolerable-but-wrong state (two boosts on the
    /// same attribute) applies fine and is flagged by `validate` instead.
    pub apply: ApplyFn<S>,
    /// Validate the slot against the fully folded state. Receives the
    /// slot's decision if one exists; emits Incomplete and Illegal entries.
    pub validate: ValidateFn<S>,
    /// Ruleset-declared gauges (see [`MetersFn`]).
    pub meters: MetersFn<S>,
    /// Render-ready description of a selection in this slot (used by the
    /// dependent-clear confirmation prompt), independent of current state.
    pub describe: Box<dyn Fn(&Selection) -> String + Send + Sync>,
}
