"""
D&D 5.5e class definitions.

Provides static data for all 13 classes available in the 2024 Player's
Handbook (plus Artificer from Tasha's Cauldron of Everything).
"""

from __future__ import annotations

from dataclasses import dataclass

from game_engine.types import Ability, CharacterClass, Skill


@dataclass(frozen=True)
class ClassData:
    """Static data describing a D&D 5.5e character class."""

    character_class: CharacterClass
    hit_die: int
    primary_abilities: list[Ability]
    saving_throw_proficiencies: list[Ability]
    armor_proficiencies: list[str]
    weapon_proficiencies: list[str]
    skill_choices: list[Skill]
    num_skill_choices: int
    spellcasting: bool


CLASSES: dict[CharacterClass, ClassData] = {
    CharacterClass.ARTIFICER: ClassData(
        character_class=CharacterClass.ARTIFICER,
        hit_die=8,
        primary_abilities=[Ability.INTELLIGENCE],
        saving_throw_proficiencies=[Ability.CONSTITUTION, Ability.INTELLIGENCE],
        armor_proficiencies=["Light", "Medium", "Shields"],
        weapon_proficiencies=["Simple weapons"],
        skill_choices=[
            Skill.ARCANA,
            Skill.HISTORY,
            Skill.INVESTIGATION,
            Skill.MEDICINE,
            Skill.NATURE,
            Skill.PERCEPTION,
            Skill.SLEIGHT_OF_HAND,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.BARBARIAN: ClassData(
        character_class=CharacterClass.BARBARIAN,
        hit_die=12,
        primary_abilities=[Ability.STRENGTH],
        saving_throw_proficiencies=[Ability.STRENGTH, Ability.CONSTITUTION],
        armor_proficiencies=["Light", "Medium", "Shields"],
        weapon_proficiencies=["Simple weapons", "Martial weapons"],
        skill_choices=[
            Skill.ANIMAL_HANDLING,
            Skill.ATHLETICS,
            Skill.INTIMIDATION,
            Skill.NATURE,
            Skill.PERCEPTION,
            Skill.SURVIVAL,
        ],
        num_skill_choices=2,
        spellcasting=False,
    ),
    CharacterClass.BARD: ClassData(
        character_class=CharacterClass.BARD,
        hit_die=8,
        primary_abilities=[Ability.CHARISMA],
        saving_throw_proficiencies=[Ability.DEXTERITY, Ability.CHARISMA],
        armor_proficiencies=["Light"],
        weapon_proficiencies=[
            "Simple weapons",
            "Hand crossbows",
            "Longswords",
            "Rapiers",
            "Shortswords",
        ],
        skill_choices=[
            Skill.ACROBATICS,
            Skill.ANIMAL_HANDLING,
            Skill.ARCANA,
            Skill.ATHLETICS,
            Skill.DECEPTION,
            Skill.HISTORY,
            Skill.INSIGHT,
            Skill.INTIMIDATION,
            Skill.INVESTIGATION,
            Skill.MEDICINE,
            Skill.NATURE,
            Skill.PERCEPTION,
            Skill.PERFORMANCE,
            Skill.PERSUASION,
            Skill.RELIGION,
            Skill.SLEIGHT_OF_HAND,
            Skill.STEALTH,
            Skill.SURVIVAL,
        ],
        num_skill_choices=3,
        spellcasting=True,
    ),
    CharacterClass.CLERIC: ClassData(
        character_class=CharacterClass.CLERIC,
        hit_die=8,
        primary_abilities=[Ability.WISDOM],
        saving_throw_proficiencies=[Ability.WISDOM, Ability.CHARISMA],
        armor_proficiencies=["Light", "Medium", "Shields"],
        weapon_proficiencies=["Simple weapons"],
        skill_choices=[
            Skill.HISTORY,
            Skill.INSIGHT,
            Skill.MEDICINE,
            Skill.PERSUASION,
            Skill.RELIGION,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.DRUID: ClassData(
        character_class=CharacterClass.DRUID,
        hit_die=8,
        primary_abilities=[Ability.WISDOM],
        saving_throw_proficiencies=[Ability.INTELLIGENCE, Ability.WISDOM],
        armor_proficiencies=["Light", "Medium", "Shields"],
        weapon_proficiencies=[
            "Clubs",
            "Daggers",
            "Darts",
            "Javelins",
            "Maces",
            "Quarterstaffs",
            "Scimitars",
            "Sickles",
            "Slings",
            "Spears",
        ],
        skill_choices=[
            Skill.ARCANA,
            Skill.ANIMAL_HANDLING,
            Skill.INSIGHT,
            Skill.MEDICINE,
            Skill.NATURE,
            Skill.PERCEPTION,
            Skill.RELIGION,
            Skill.SURVIVAL,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.FIGHTER: ClassData(
        character_class=CharacterClass.FIGHTER,
        hit_die=10,
        primary_abilities=[Ability.STRENGTH, Ability.DEXTERITY],
        saving_throw_proficiencies=[Ability.STRENGTH, Ability.CONSTITUTION],
        armor_proficiencies=["Light", "Medium", "Heavy", "Shields"],
        weapon_proficiencies=["Simple weapons", "Martial weapons"],
        skill_choices=[
            Skill.ACROBATICS,
            Skill.ANIMAL_HANDLING,
            Skill.ATHLETICS,
            Skill.HISTORY,
            Skill.INSIGHT,
            Skill.INTIMIDATION,
            Skill.PERCEPTION,
            Skill.SURVIVAL,
        ],
        num_skill_choices=2,
        spellcasting=False,
    ),
    CharacterClass.MONK: ClassData(
        character_class=CharacterClass.MONK,
        hit_die=8,
        primary_abilities=[Ability.DEXTERITY, Ability.WISDOM],
        saving_throw_proficiencies=[Ability.STRENGTH, Ability.DEXTERITY],
        armor_proficiencies=[],
        weapon_proficiencies=["Simple weapons", "Shortswords"],
        skill_choices=[
            Skill.ACROBATICS,
            Skill.ATHLETICS,
            Skill.HISTORY,
            Skill.INSIGHT,
            Skill.RELIGION,
            Skill.STEALTH,
        ],
        num_skill_choices=2,
        spellcasting=False,
    ),
    CharacterClass.PALADIN: ClassData(
        character_class=CharacterClass.PALADIN,
        hit_die=10,
        primary_abilities=[Ability.STRENGTH, Ability.CHARISMA],
        saving_throw_proficiencies=[Ability.WISDOM, Ability.CHARISMA],
        armor_proficiencies=["Light", "Medium", "Heavy", "Shields"],
        weapon_proficiencies=["Simple weapons", "Martial weapons"],
        skill_choices=[
            Skill.ATHLETICS,
            Skill.INSIGHT,
            Skill.INTIMIDATION,
            Skill.MEDICINE,
            Skill.PERSUASION,
            Skill.RELIGION,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.RANGER: ClassData(
        character_class=CharacterClass.RANGER,
        hit_die=10,
        primary_abilities=[Ability.DEXTERITY, Ability.WISDOM],
        saving_throw_proficiencies=[Ability.STRENGTH, Ability.DEXTERITY],
        armor_proficiencies=["Light", "Medium", "Shields"],
        weapon_proficiencies=["Simple weapons", "Martial weapons"],
        skill_choices=[
            Skill.ANIMAL_HANDLING,
            Skill.ATHLETICS,
            Skill.INSIGHT,
            Skill.INVESTIGATION,
            Skill.NATURE,
            Skill.PERCEPTION,
            Skill.STEALTH,
            Skill.SURVIVAL,
        ],
        num_skill_choices=3,
        spellcasting=True,
    ),
    CharacterClass.ROGUE: ClassData(
        character_class=CharacterClass.ROGUE,
        hit_die=8,
        primary_abilities=[Ability.DEXTERITY],
        saving_throw_proficiencies=[Ability.DEXTERITY, Ability.INTELLIGENCE],
        armor_proficiencies=["Light"],
        weapon_proficiencies=[
            "Simple weapons",
            "Hand crossbows",
            "Longswords",
            "Rapiers",
            "Shortswords",
        ],
        skill_choices=[
            Skill.ACROBATICS,
            Skill.ATHLETICS,
            Skill.DECEPTION,
            Skill.INSIGHT,
            Skill.INTIMIDATION,
            Skill.INVESTIGATION,
            Skill.PERCEPTION,
            Skill.PERFORMANCE,
            Skill.PERSUASION,
            Skill.SLEIGHT_OF_HAND,
            Skill.STEALTH,
        ],
        num_skill_choices=4,
        spellcasting=False,
    ),
    CharacterClass.SORCERER: ClassData(
        character_class=CharacterClass.SORCERER,
        hit_die=6,
        primary_abilities=[Ability.CHARISMA],
        saving_throw_proficiencies=[Ability.CONSTITUTION, Ability.CHARISMA],
        armor_proficiencies=[],
        weapon_proficiencies=[
            "Daggers",
            "Darts",
            "Slings",
            "Quarterstaffs",
            "Light crossbows",
        ],
        skill_choices=[
            Skill.ARCANA,
            Skill.DECEPTION,
            Skill.INSIGHT,
            Skill.INTIMIDATION,
            Skill.PERSUASION,
            Skill.RELIGION,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.WARLOCK: ClassData(
        character_class=CharacterClass.WARLOCK,
        hit_die=8,
        primary_abilities=[Ability.CHARISMA],
        saving_throw_proficiencies=[Ability.WISDOM, Ability.CHARISMA],
        armor_proficiencies=["Light"],
        weapon_proficiencies=["Simple weapons"],
        skill_choices=[
            Skill.ARCANA,
            Skill.DECEPTION,
            Skill.HISTORY,
            Skill.INTIMIDATION,
            Skill.INVESTIGATION,
            Skill.NATURE,
            Skill.RELIGION,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
    CharacterClass.WIZARD: ClassData(
        character_class=CharacterClass.WIZARD,
        hit_die=6,
        primary_abilities=[Ability.INTELLIGENCE],
        saving_throw_proficiencies=[Ability.INTELLIGENCE, Ability.WISDOM],
        armor_proficiencies=[],
        weapon_proficiencies=[
            "Daggers",
            "Darts",
            "Slings",
            "Quarterstaffs",
            "Light crossbows",
        ],
        skill_choices=[
            Skill.ARCANA,
            Skill.HISTORY,
            Skill.INSIGHT,
            Skill.INVESTIGATION,
            Skill.MEDICINE,
            Skill.RELIGION,
        ],
        num_skill_choices=2,
        spellcasting=True,
    ),
}
