"""
D&D 5.5e class definitions.

Provides static data for all 13 classes available in the 2024 Player's
Handbook (plus Artificer from Tasha's Cauldron of Everything).
"""

from __future__ import annotations

#: Complete class data for all 13 D&D 5.5e classes.
#:
#: Keys per class:
#:   hit_die                    – size of the class hit die
#:   primary_ability            – governing ability score for the class
#:   saving_throw_proficiencies – ability scores the class is proficient in saving throws for
#:   armor_proficiencies        – armour types the class can wear proficiently
#:   weapon_proficiencies       – weapon categories/types the class is proficient with
#:   skill_choices              – skill list to choose from at character creation
#:   num_skill_choices          – how many skills to pick from skill_choices
#:   spellcasting               – whether the class can cast spells
CLASSES: dict[str, dict] = {
    "Artificer": {
        "hit_die": 8,
        "primary_ability": "Intelligence",
        "saving_throw_proficiencies": ["Constitution", "Intelligence"],
        "armor_proficiencies": ["Light", "Medium", "Shields"],
        "weapon_proficiencies": ["Simple weapons"],
        "skill_choices": [
            "Arcana",
            "History",
            "Investigation",
            "Medicine",
            "Nature",
            "Perception",
            "Sleight of Hand",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Barbarian": {
        "hit_die": 12,
        "primary_ability": "Strength",
        "saving_throw_proficiencies": ["Strength", "Constitution"],
        "armor_proficiencies": ["Light", "Medium", "Shields"],
        "weapon_proficiencies": ["Simple weapons", "Martial weapons"],
        "skill_choices": [
            "Animal Handling",
            "Athletics",
            "Intimidation",
            "Nature",
            "Perception",
            "Survival",
        ],
        "num_skill_choices": 2,
        "spellcasting": False,
    },
    "Bard": {
        "hit_die": 8,
        "primary_ability": "Charisma",
        "saving_throw_proficiencies": ["Dexterity", "Charisma"],
        "armor_proficiencies": ["Light"],
        "weapon_proficiencies": [
            "Simple weapons",
            "Hand crossbows",
            "Longswords",
            "Rapiers",
            "Shortswords",
        ],
        "skill_choices": [
            "Acrobatics",
            "Animal Handling",
            "Arcana",
            "Athletics",
            "Deception",
            "History",
            "Insight",
            "Intimidation",
            "Investigation",
            "Medicine",
            "Nature",
            "Perception",
            "Performance",
            "Persuasion",
            "Religion",
            "Sleight of Hand",
            "Stealth",
            "Survival",
        ],
        "num_skill_choices": 3,
        "spellcasting": True,
    },
    "Cleric": {
        "hit_die": 8,
        "primary_ability": "Wisdom",
        "saving_throw_proficiencies": ["Wisdom", "Charisma"],
        "armor_proficiencies": ["Light", "Medium", "Shields"],
        "weapon_proficiencies": ["Simple weapons"],
        "skill_choices": [
            "History",
            "Insight",
            "Medicine",
            "Persuasion",
            "Religion",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Druid": {
        "hit_die": 8,
        "primary_ability": "Wisdom",
        "saving_throw_proficiencies": ["Intelligence", "Wisdom"],
        "armor_proficiencies": ["Light", "Medium", "Shields"],
        "weapon_proficiencies": [
            "Clubs",
            "Daggers",
            "Darts",
            "Javelins",
            "Maces",
            "Quarterstaffs",
            "Scimitars",
            "Sickles",
            "Slings",
            "Spears",
        ],
        "skill_choices": [
            "Arcana",
            "Animal Handling",
            "Insight",
            "Medicine",
            "Nature",
            "Perception",
            "Religion",
            "Survival",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Fighter": {
        "hit_die": 10,
        "primary_ability": "Strength or Dexterity",
        "saving_throw_proficiencies": ["Strength", "Constitution"],
        "armor_proficiencies": ["Light", "Medium", "Heavy", "Shields"],
        "weapon_proficiencies": ["Simple weapons", "Martial weapons"],
        "skill_choices": [
            "Acrobatics",
            "Animal Handling",
            "Athletics",
            "History",
            "Insight",
            "Intimidation",
            "Perception",
            "Survival",
        ],
        "num_skill_choices": 2,
        "spellcasting": False,
    },
    "Monk": {
        "hit_die": 8,
        "primary_ability": "Dexterity and Wisdom",
        "saving_throw_proficiencies": ["Strength", "Dexterity"],
        "armor_proficiencies": [],
        "weapon_proficiencies": ["Simple weapons", "Shortswords"],
        "skill_choices": [
            "Acrobatics",
            "Athletics",
            "History",
            "Insight",
            "Religion",
            "Stealth",
        ],
        "num_skill_choices": 2,
        "spellcasting": False,
    },
    "Paladin": {
        "hit_die": 10,
        "primary_ability": "Strength and Charisma",
        "saving_throw_proficiencies": ["Wisdom", "Charisma"],
        "armor_proficiencies": ["Light", "Medium", "Heavy", "Shields"],
        "weapon_proficiencies": ["Simple weapons", "Martial weapons"],
        "skill_choices": [
            "Athletics",
            "Insight",
            "Intimidation",
            "Medicine",
            "Persuasion",
            "Religion",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Ranger": {
        "hit_die": 10,
        "primary_ability": "Dexterity and Wisdom",
        "saving_throw_proficiencies": ["Strength", "Dexterity"],
        "armor_proficiencies": ["Light", "Medium", "Shields"],
        "weapon_proficiencies": ["Simple weapons", "Martial weapons"],
        "skill_choices": [
            "Animal Handling",
            "Athletics",
            "Insight",
            "Investigation",
            "Nature",
            "Perception",
            "Stealth",
            "Survival",
        ],
        "num_skill_choices": 3,
        "spellcasting": True,
    },
    "Rogue": {
        "hit_die": 8,
        "primary_ability": "Dexterity",
        "saving_throw_proficiencies": ["Dexterity", "Intelligence"],
        "armor_proficiencies": ["Light"],
        "weapon_proficiencies": [
            "Simple weapons",
            "Hand crossbows",
            "Longswords",
            "Rapiers",
            "Shortswords",
        ],
        "skill_choices": [
            "Acrobatics",
            "Athletics",
            "Deception",
            "Insight",
            "Intimidation",
            "Investigation",
            "Perception",
            "Performance",
            "Persuasion",
            "Sleight of Hand",
            "Stealth",
        ],
        "num_skill_choices": 4,
        "spellcasting": False,
    },
    "Sorcerer": {
        "hit_die": 6,
        "primary_ability": "Charisma",
        "saving_throw_proficiencies": ["Constitution", "Charisma"],
        "armor_proficiencies": [],
        "weapon_proficiencies": [
            "Daggers",
            "Darts",
            "Slings",
            "Quarterstaffs",
            "Light crossbows",
        ],
        "skill_choices": [
            "Arcana",
            "Deception",
            "Insight",
            "Intimidation",
            "Persuasion",
            "Religion",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Warlock": {
        "hit_die": 8,
        "primary_ability": "Charisma",
        "saving_throw_proficiencies": ["Wisdom", "Charisma"],
        "armor_proficiencies": ["Light"],
        "weapon_proficiencies": ["Simple weapons"],
        "skill_choices": [
            "Arcana",
            "Deception",
            "History",
            "Intimidation",
            "Investigation",
            "Nature",
            "Religion",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
    "Wizard": {
        "hit_die": 6,
        "primary_ability": "Intelligence",
        "saving_throw_proficiencies": ["Intelligence", "Wisdom"],
        "armor_proficiencies": [],
        "weapon_proficiencies": [
            "Daggers",
            "Darts",
            "Slings",
            "Quarterstaffs",
            "Light crossbows",
        ],
        "skill_choices": [
            "Arcana",
            "History",
            "Insight",
            "Investigation",
            "Medicine",
            "Religion",
        ],
        "num_skill_choices": 2,
        "spellcasting": True,
    },
}
